export const UPDATE_APP_BAR_TITLE = 'UPDATE_APP_BAR_TITLE';
export const UPDATE_CATS = 'UPDATE_CATS';
export const UPDATE_CATS_TOTAL = 'UPDATE_CATS_TOTAL';
export const UPDATE_CAT_LIST_PAGE = 'UPDATE_CAT_LIST_PAGE';
export const UPDATE_CAT_TEMPLATE = 'UPDATE_CAT_TEMPLATE';
export const UPDATE_PART_CAT_TEMPLATE = 'UPDATE_PART_CAT_TEMPLATE';
export const UPDATE_CAT_NAME = 'UPDATE_CAT_NAME';
export const TOGGLE_TOAST = 'TOGGLE_TOAST';
